sudo: false
language: 
  - ruby
rvm:
  - 2.1.1
env:
  - DB=default
  - DB=postgres
before_script:
  - bundle exec rake db:preprep
  - psql -c 'create database rsense_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_install:
  - "gem install bundler --version '>= 1.5.1'"
  - bundle install
  - add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
  - apt-get install -qq libreoffice libreoffice-calc unoconv
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - libreoffice --headless --accept="socket,host=0,port=8001,tcpNoDelay=1;urp" --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --invisible &
